### ISSUE TITLE
Unicenta 4.2

### ISSUE THREAD

**Issue by Iwan2323** [herbiehp/unicenta#10]
Hello,

i have downloaded unicentaopos-4.2,
but an error when I run it
![4 2](https://user-images.githubusercontent.com/29030451/30953525-87923b9e-a456-11e7-812b-fa6d54f3611f.png)

I am using Linux OS 14.04
Java version 7 and 8
is there anybody who can help me?

Regards,
Iwan Gunawan

**Comment by herbiehp** [comment]
Dear Iwan,
my last used version was 3.9 and it still runs well, so 4.2 you had to be download from another source. However, you are using an unsupported  jar/lib version, please speak with the developers of 4.2 or check the compatibility list.
Regards, Herb

**Comment by Iwan2323** [comment]
Hello Herb,
thanks for your response,
I have also been using unicenta version 3.9 and still runs well, but i just try to use unicenta 4.2, I just want to know the difference

Regards, Iwan

**Comment by kokowawaa** [comment]
You have unicenta 4.5.1
