### ISSUE TITLE
Plans for this repo?

### ISSUE THREAD

**Issue by TekMason** [herbiehp/unicenta#2]
Hi herbiehp,

What are your plans for this repo?
I would like to make it my primary uniCenta development repository if you aren't going way out on a limb with it.

I am a noob to GitHub and Java but there are a lot of simple things that I can do (minor code changes, images, form design and documentation) to free up the gurus so they can focus on the important stuff.

Sorry if this is not the proper forum to use for this inquiry but I don't know how else to contact you.

TekMason
![image](https://cloud.githubusercontent.com/assets/2549612/5601646/57475c32-92dc-11e4-9c17-a32d33a994ef.png)

**Comment by herbiehp** [comment]
I would like to keep it as close to the trunk as possible!
