### ISSUE TITLE
Modify Customer Form

### ISSUE THREAD

**Issue by TekMason** [herbiehp/unicenta#3]
Modify customer form to add additional attributes that are check boxes (like visible) and add columns to the customers table to store them.

To make it generic and usable by any business the names displayed in the GUI (and field names) should be something like CustAttr1, CustAttr2, etc with the ability to change the name displayed in the GUI with a Resources file.

A use case is for an organization that offers memberships to its customers.
Example
A country club that runs golf, curling and tennis operations.
It would be useful for them to track customer memberships and the types in uniCenta.
Some types could be:
- Golf Membership - Full
- Golf Membership - Weekdays
- Curling Membership - Full
- Curling Membership - 1 night per week
- Tennis Membership - Full

I am willing to take this on but don't know where to start on this yet so I may need some help.

Thx,
TekMason

**Comment by herbiehp** [comment]
Now we would need the lead here.

Just a suggestion - let us not extend the core table for now, let us a table membership to the shema, as we would manipulate the core and generate us some problem with carrying about this extensions anyway. Yes it will be a joined select, and I don't know Derby well enough to estimate the performance once we start with joined tables. However the volume is low.
