### ISSUE TITLE
Fix JRE Detection Routine in Setup

### ISSUE THREAD

**Issue by TekMason** [herbiehp/unicenta#5]
Setup does not detect JRE 8u25 (and probably other JRE 8 versions) properly and throws an error messages.  Not a good start for a new user.

To reproduce the issue:
On a clean Window 7 x64 PC
Install jre-8u25-windows-x64.exe
Check Java
_C:\Users\MMason>set path
Path=C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
C:>
C:>java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
C:>_
Installed unicentaopos-3.81-windows-installer.exe
 ![setuperror1](https://cloud.githubusercontent.com/assets/2549612/5605514/8c988e3c-93cd-11e4-9a00-be9188631c0f.png)
Click OK
browser window opens up to http://www.java.com/en/ and
![setuperror2](https://cloud.githubusercontent.com/assets/2549612/5605515/8f59fda4-93cd-11e4-954a-85de149e2936.png)
Click OK
Normal setup screen appears
![setup3](https://cloud.githubusercontent.com/assets/2549612/5605516/92ef6602-93cd-11e4-935b-492f4edcd37d.png)

**Comment by herbiehp** [comment]
## If you look at the file unicentaopso_3.81_installer.xml you will find the text below.  1.7 is required to wrk with unicentaopos or you cannot use the installer. I am not aware if it runs with 1.8, I didn't test it by now, theoretically the versions would be compatible.

```
<preInstallationActionList>
    <autodetectJava>
        <abortOnError>0</abortOnError>
        <customErrorMessage>Java JRE not found on your machine. Install the correct Java JRE runtime and then continue with install.</customErrorMessage>
        <explanation>Checking for Java JRE</explanation>
        <progressText>Searching....</progressText>
        <promptUser>1</promptUser>
        <selectionOrder>newest</selectionOrder>
        <onErrorActionList>
            <showInfo>
                <explanation>When done...
```

Please use the JRE 1.7 version located in your Windows\System32</explanation>
                    <text>Couldn't find Java JRE runtime on your machine!
Opening the Java website for you

Install the correct Java JRE runtime for your machine

Then continue with uniCenta oPOS installation.</text>
                </showInfo>
                <launchBrowser>
                    <url>http://www.java.com</url>
                </launchBrowser>
            </onErrorActionList>
            <validVersionList>
                <validVersion>
                    <bitness></bitness>
                    <maxVersion>1.7</maxVersion>
                    <minVersion>1.7</minVersion>
                    <requireJDK>0</requireJDK>
                    <vendor>sun</vendor>
                </validVersion>
            </validVersionList>
        </autodetectJava>
    </preInstallationActionList>

**Comment by herbiehp** [comment]
Sorry for the fonts something was mixed up.

**Comment by TekMason** [comment]
Thanks for the info herbiehp.  Me thinks TekMason will learn a lot from you here.

Unfortunately none of the error messages tell the user that JRE 7 (1.7)  is required (see screen shots).  The only mention of JRE prerequisites I've ever seen is "JRE 7 or later".  Furthermore, Oracle has declared JRE 7 End of Life on the Java SE Runtime Environment 7 Downloads site.
http://www.oracle.com/technetwork/java/javase/downloads/jre7-downloads-1880261.html

**With that in mind could we reopen this issue as a enhancement?**

BTW I am running uniCenta with JRE 1.8 in my test environment without issue so far...

TekMason

**Comment by herbiehp** [comment]
I don't see why 1.8 should not be used, but its all about the installer and its definition. The alternative is to change the installer script and use http://installbuilder.bitrock.com/ to generate a new installer by setting the value of max version to 1.8 for java.

**Comment by KrayemLy** [comment]
I've tested jre 1.8 when unicenta 3.70 released and all runs fine except reports
i think it was a problem with jasperReports library
