### ISSUE TITLE
Add an Optional Configuration Selector on Startup

### ISSUE THREAD

**Issue by TekMason** [herbiehp/unicenta#7]
Add an Optional Configuration Selector that can prompt for a configuration selection when uniCenta starts.  See below for a model of how this could work.

uniCenta POS / Discussion / Help:Dual configuration files (unicentaopos.properties)?
https://sourceforge.net/p/unicentaopos/discussion/1126901/thread/401e3b13/?limit=25#bfa0

**Comment by herbiehp** [comment]
What would be the goal here, a POS that is used for two separate type of usage on one computer?
